version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      # Compartir la carpeta de deployments de WildFly en Windows
      - /c/wildfly-19.1.0.Final/standalone/deployments:/deployments

volumes:
  jenkins_home:
